project:
  type: book
  output-dir: docs

toc: true
number-sections: true
toc-depth: 2
number-depth: 4
bibliography: book.bib
csl: C:/Users/Xinli/Documents/ims.csl

format:
  html:
    theme: zephyr
    split_by: section
  pdf:
    documentclass: scrreprt

book:
  title: "Python/R for Data Science"
  subtitle: "Lecture notes for 2022 Fall at Arkansas Tech University"
  author: "Xinli Xiao"
  date: last-modified
  downloads: [pdf]
  chapters: 
    - index.qmd
    - part: "Part I: Python"
      chapters: 
        # - contents/1/01-.qmd
        # - contents/2/02-.qmd
        - contents/3/03-.qmd
    #     - contents/4/04-.qmd
    # - part: "Part II: R"
    #   chapters:
    #     - contents/5/05-.qmd
    - contents/references.qmd
  sidebar:
    style: floating
    border: true
    search: true
    collapse-level: 1
    pinned: false
  navbar:
    subtitle: "2022 Fall"
  page-navigation: true


    



