## Exercises



::: {#exr-}
Which of these are character strings and which are numbers? `1`, `"1"`, `"one"`.
:::


::: {#exr-}
Create an atomic vector that stores just the face names of the cards: the ace of spades, king of spades, queen of spades, jack of spades, and ten of spades. Which type of vector will you use to save the names?

Hint: The face name of the ace of spades would be `ace` and `spades` is the suit.
:::



::: {#exr-}
Create the following matrix, which stores the name and suit of every card in a royal flush.

```{r}
#| echo: false
hand <- c("ace", "spades", "king", "spades", "queen", "spades", "jack", "spades", "ten", "spades")
matrix(hand, ncol=2, byrow=TRUE)
```
:::



::: {#exr-}
Many card games assign a numerical value to each card. For example, in blackjack, each face card is worth 10 points, each number card is worth between 2 and 10 points, and each ace is worth 1 or 11 points, depending on the final score.

Make a virtual playing card by combining “ace” “heart” and 1 into a vector. What type of atomic vector will result? Check if you are right, and explain your reason.
:::



::: {#exr-}
Use a list to store a single playing card, like the ace of hearts, which has a point value of one. The list should save the face of the card, the suit, and the point value in separate elements.
:::